version: '2'

services:
  pg:
    build:
      context: .
      dockerfile: postgres.dockerfile
    image: pg
    container_name: pg
    restart: always
    environment:
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - axum-postgres
  axum-server:
    build:
      context: .
      dockerfile: axum.dockerfile
    image: axum-server
    container_name: axum-server
    ports:
      - 3000:3000
    depends_on:
      - pg
    networks:
      - axum-postgres

networks:
  axum-postgres:
